### ISSUE TITLE
Chyba s popisem obrazové přílohy

### ISSUE THREAD

**Issue by geckot** [JarkaP/hiko#37]
Všimli jsme si, že se seznam dopisů někdy tváří, že zadaná korespondenční jednotka obsahuje obrazovou přílohu, ve skutečnosti tomu tak ale není. Například dopis TGM – Robert William Seton Watson, 1912/3/23 se v seznamu chybně tváří, že obsahuje obrázky. Nevylučuji, že se problém bude opakovat na více místech, dodatečně za tímto účelem překontroluji celou korespondenci TGM.

**Comment by JarkaP** [comment]
Mělo by to už být opravené.
