### ISSUE TITLE
Ampsersand

### ISSUE THREAD

**Issue by geckot** [JarkaP/hiko#50]
V seznamu dopisů se pod polem signature opětovně zobrazuje problém s ampersandem, tj. zobrazuje se &amp. Při otevření samotné šablony dopisu tento problém není. Například dopis Masaryk – Husserl, 20. 1. 1878. Bylo by prosím možno odstranit.

**Comment by JarkaP** [comment]
Opravené

**Comment by geckot** [comment]
skvělé, moc děkuji!
Tomáš G.

________________________________
Od: Jarka Pachlová <notifications@github.com>
Odesláno: pondělí 16. listopadu 2020 1:42
Komu: JarkaP/hiko <hiko@noreply.github.com>
Kopie: PhDr. Bc. Tomáš Gecko, Ph.D. <gecko@mua.cas.cz>; Author <author@noreply.github.com>
Předmět: Re: [JarkaP/hiko] Ampsersand (#50)


Opravené
