### ISSUE TITLE
instituce jako autor / příjemce

### ISSUE THREAD

**Issue by JarkaP** [JarkaP/hiko#6]
Jak vyřešit, pokud je autorem či příjemcem instituce?

**Comment by geckot** [comment]
Navazuji na tuto otázku, protože se pro nás nyní stala vysoce aktuální. V tuto chvíli narážíme na problém, kdy je pisatelem či adresátem instituce. Bylo by tuto možnost zohlednit do záložky "lidé"? Třeba na začátku umožnit dvojí volbu, a to zda se jedná o "osobu" či "instituci"? Pokud by se jednalo o instituci, prozatím bychom vyplňovali pouze její název.

**Comment by JarkaP** [comment]
Místo osob je teď možné vkládat osoby / instituce – ve formuláři, který byl původně jen pro osoby, se dá vybrat možnost 'instituce', v přehledu lidí a institucí se pak zobrazí, o jaký typ jde. Při vytváření dopisu jako takového a v náhledu to zatím není nijak zohledněno.
