### ISSUE TITLE
MS Manifestation (EMLO)

### ISSUE THREAD

**Issue by geckot** [JarkaP/hiko#70]
Jestliže do vyplněného formuláře dopisu vložíme prostřednictví "add" jakoukoliv novou položku (origin, destination, author, recipient, related resource), anebo když tuto položku jakkoliv edituji, odmaže se vyplnění MS Manifestation (EMLO). Zjistil jsem, že napříč vloženými dopisy je MS Manifestation (EMLO) odmazáno, zřejmě tedy došlo ke ztrátě dat.

Při vložení nové položky přes "add" se ve formuláři krátce objeví vyplněná následující hodnota [{"value":"","id":""}]. Před aktualizací databáze tomu tak nebylo.

**Comment by JarkaP** [comment]
1) MS Manifestation se už zobrazuje správně.

2) Ve chvíli, kdy tam problikne tahle zpráva, tak se inicializuje seznam dat k vyplnění, je to zamýšlené (a matoucí, upravím to, viz #73 ).
