### ISSUE TITLE
Osoby a instituce

### ISSUE THREAD

**Issue by geckot** [JarkaP/hiko#75]
V seznamu osob a institucí narážím na množství nesrovnalostí v poli "Name as marked". Pod konkrétním jménem se řadí v poli as marked i zcela odlišné osobnosti. Může se jednat o chyby editorů zadávajících do databáze dopisy, prokotroloval jsem však většinu korespondence TGM a podobných problémů jsem si nevšiml. Viz Eduard Bernstein a přiřazení A. Steinbergerová; Emil Abderhalden a přiřazení Frederick Dixon; David Albala a přiřazení Arthur J. Balfour.

**Comment by JarkaP** [comment]
V seznamu osob / institucí by u každé položky měl jít přegenerovat seznam jmen a vyřadit tak staré / nesprávné údaje.

**Comment by JarkaP** [comment]
(Změny se projeví až při novém načtení panelu s tabulkou.)
