### ISSUE TITLE
Manifestations and repositories

### ISSUE THREAD

**Issue by geckot** [JarkaP/hiko#76]
V manifestations and repositories nelze zadat visiting card v poli Document type, pouze visiting. Bylo by prosím možné upravit jak při výběru kategorie do pole, tak u již vložených polí?

Editoři hlásí problém také se zadáváním handwritten/typewritten v poli Type of Copy. Při několika pokusech o vložení se neuložilo.

**Comment by JarkaP** [comment]
Problém se zadáváním handwritten/typewritten se mi nedaří nasimulovat, trochu jsem to pole upravila, podíváte se prosím, zda ten problém přetrvává?
