### ISSUE TITLE
Export konkrétní skupiny záznamů

### ISSUE THREAD

**Issue by Krubnerova** [JarkaP/hiko#79]
Prosím o radu, jak vyexportovat pouze skupinu dopisů, např. podle konkrétního filtru (jméno, datum ap.), a to do excelové tabulky tak, aby v ní bylo obsaženo i ID dopisu. Nyní mi to nabízí pouze "export všech záznamů Palladio"a v tabulce není ID. Moc děkuji. V. Krubnerová

**Comment by JarkaP** [comment]
Dobrý den, když mi napíšete, jaká data chcete a v jakém formátu, tak to připravím na míru tomu, co potřebujete. Export podle filtrů zatím není možný.

**Comment by JarkaP** [comment]
(ID je přidané do obecného exportu)
